var territoryTypes=[
	{
		name:'field',
		isBarrier:false,
		ambush:{
			infantry: false,
			artillery:false,
			vehicle:false,
			armoredVehicle:false,
			lightTank:false,
			heavyTank:false,
			helicoter:false,
			lightAircraft:false,
			heavyAircraft:false
		},
		infantryTrench:true,
		tankTrench:true,
		pillbox:true,
		loadingType:'easy'
	},
	{
		name:'bush',
		isBarrier:true,
		ambush:{
			infantry: true,
			artillery:false,
			vehicle:false,
			armoredVehicle:false,
			lightTank:false,
			heavyTank:false,
			helicoter:false,
			lightAircraft:false,
			heavyAircraft:false
		},
		infantryTrench:true,
		tankTrench:true,
		pillbox:true,
		loadingType:'easy'
	},
	{
		name:'river',
		isBarrier:false,
		ambush:{
			infantry: true,
			artillery:false,
			vehicle:false,
			armoredVehicle:false,
			lightTank:false,
			heavyTank:false,
			helicoter:false,
			lightAircraft:false,
			heavyAircraft:false
		},
		infantryTrench:false,
		tankTrench:false,
		pillbox:false,
		loadingType:'hard'
	}
];